### ISSUE TITLE
Segmentation faults

### ISSUE THREAD

**Issue by cmovcc** [Cotrik/CotrikMesh#1]
Hello !

We (@dwarfmaster and I) are trying to build the tools in this repository, and so far we did succeed at compiling all of the tools, but most of them raise a segfault when executed on libgeodesic_heart/test/ .vtk files.

With the following commands, we get the following errors:
```shell
$ ./apps/ExtractBaseComplex ../libgeodesic_heart/test/bunny.tet.vtk 
---------------------------------------
filename = ../libgeodesic_heart/test/bunny.tet.vtk
---------------------------------------
../libgeodesic_heart/test/bunny.tet.vtk UnstructuredGrid: 40107 points 164419 cells
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 230676)
Aborted (core dumped)

$ ./apps/ExtractBaseComplex ../libgeodesic_heart/test/SharpEdges.vtk 
---------------------------------------
filename = ../libgeodesic_heart/test/SharpEdges.vtk
---------------------------------------
../libgeodesic_heart/test/SharpEdges.vtk PolyData: 40107 points 0 polys
Segmentation fault (core dumped)
```

I tried on Arch Linux, with :
- gcc-10.2.0-3 and gcc-9 (gcc-8 would require an older glibc version, I didn't try)
- glibc 2.32-4
(the following packages were the ones required to make on my setup)
- vtk 8.2.0-14
- proj 6.3.2-1
- netcdf 4.7.4-1
- gdal 3.0.4-13
- pugixml 1.10-2
- unixodbc 2.3.9-1
- pdal 2.1.0-1

We both tried using `cmake ..` after installing all of the dependencies that seemed to be required, as we were not very keen to use `ccmake ..`.

**Comment by dwarfmaster** [comment]
I encountered the exact same problem while trying under NixOS, using the following nix configuration : 

`flake.nix` :
```nix

{
  description = "Hexahedral mesh extraction";

  inputs = {
    nixpkgs.url = github:NixOS/nixpkgs/nixos-20.09;
  };

  outputs = { self, nixpkgs }:
    let
      system           = "x86_64-linux";
      pkgs             = nixpkgs.legacyPackages.${system};
      stdenv           = pkgs.overrideCC pkgs.stdenv pkgs.clang;
      git-ignore       = pkgs.nix-gitignore.gitignoreSourcePure;
      pkg              = stdenv.mkDerivation {
        name = "cotrikmesh";
        src = git-ignore [ ./.gitignore ] ./.;
        buildInputs = with pkgs; [ cmake gnumake eigen vtk ];
      };
    in {
      packages.${system} = {
        window = pkg;
      };
      defaultPackage.${system} = self.packages.${system}.window;
    };
}
```

And

`flake.lock` :
```json
{
  "nodes": {
    "nixpkgs": {
      "locked": {
        "lastModified": 1601200199,
        "narHash": "sha256-wf5XDJJ8tJw0gZH7S1+r/I/k321bj9jGVzRXEVtbfkQ=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "0cfe5377e8993052f9b0dd56d058f8008af45bd9",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixos-20.09",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "nixpkgs": "nixpkgs"
      }
    }
  },
  "root": "root",
  "version": 7
}
```

**Comment by naeem014** [comment]
Can you input a hex.vtk (hexahedral mesh) to the ExtractBaseComplex program? This library only implements the base complex extraction for Hexahedral meshes. The programs in the apps directory contain a generic description for types of inputs and outputs needed. 

For your second error output, the input vtk file contains edges only and thus cannot be used for the ExtractBaseComplex program. Please let us know if you further questions.

**Comment by dwarfmaster** [comment]
Thank you for the quick answer ! Do you know where we can find an hexahedral mesh/how we can create one ?

**Comment by Cotrik** [comment]
Hi Luc,

There are some models  in
https://github.com/cnr-isti-vclab/HexaLab/find/master.

Best,
Kaoji

**Comment by Cotrik** [comment]
There are some models  in https://github.com/cnr-isti-vclab/HexaLab/find/master.

**Comment by dwarfmaster** [comment]
Thanks a lot, I managed to get it working ! It's taking an awful long time on some models, but it does produce results.

**Comment by cmovcc** [comment]
Thank you!
